title: virtual void  
description: void some vocabulary for programming in the large
theme: just-the-docs

url: https://www.bitfactory.at

permalink: pretty

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
